name: aclub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_settings_ui: ^3.0.1
  flutter_svg: ^2.0.0
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.0.0
  flutter_screenutil: ^5.6.0
  http: ^1.2.2
  shared_preferences: ^2.0.0
  url_launcher: ^6.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^18.0.1
  flutter_pdfview: ^1.2.7
  dio: ^5.0.10
  permission_handler: ^11.3.1
  open_file: ^3.2.1
  flutter_downloader: ^1.7.11
  intl: ^0.19.0
  lottie: ^3.1.3
  sliding_up_panel: ^2.0.0+1
  animations: ^2.0.5
  percent_indicator: ^4.2.2
  fluttertoast: ^8.0.9
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.1
  convex_bottom_bar: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  bottom_navy_bar: ^6.1.0
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/ACLUB.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/ACLUB.png"
    background_color: "#FF5733"
    theme_color: "#C70039"
  windows:
    generate: true
    image_path: "assets/logo/ACLUB.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/ACLUB.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/files/
    - assets/
